server:
  port: 8782
  context-path: /eureka2
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaltZone: http://peer1:8761/eureka/
spring:
  application:
    name: eureka-client-2